services:
  azure-openai-proxy:
    restart: always
    image: whatwewant/azure-openai-proxy:${SERVICE_AZURE_OPENAI_PROXY_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_AZURE_OPENAI_PROXY_PORT}:8080
    environment:
      PORT: $SERVICE_AZURE_OPENAI_PROXY_PORT
      BASE_PATH: ${SERVICE_AZURE_OPENAI_PROXY_BASE_PATH}
      AUTH_TOKEN: ${SERVICE_AZURE_OPENAI_PROXY_AUTH_TOKEN}
      # chat completion
      #   1. gpt-3.5
      CHAT_COMPLETION_RESOURCE_FOR_GPT35: ${SERVICE_AZURE_OPENAI_PROXY_CHAT_COMPLETION_RESOURCE_FOR_GPT35}
      CHAT_COMPLETION_DEPLOYMENT_FOR_GPT35: ${SERVICE_AZURE_OPENAI_PROXY_CHAT_COMPLETION_DEPLOYMENT_FOR_GPT35}
      CHAT_COMPLETION_API_KEY_FOR_GPT35: ${SERVICE_AZURE_OPENAI_PROXY_CHAT_COMPLETION_API_KEY_FOR_GPT35}
      CHAT_COMPLETION_API_VERSION_FOR_GPT35: ${SERVICE_AZURE_OPENAI_PROXY_CHAT_COMPLETION_API_VERSION_FOR_GPT35}
      #   2. gpt-4
      CHAT_COMPLETION_RESOURCE_FOR_GPT4: ${SERVICE_AZURE_OPENAI_PROXY_CHAT_COMPLETION_RESOURCE_FOR_GPT4}
      CHAT_COMPLETION_DEPLOYMENT_FOR_GPT4: ${SERVICE_AZURE_OPENAI_PROXY_CHAT_COMPLETION_DEPLOYMENT_FOR_GPT4}
      CHAT_COMPLETION_API_KEY_FOR_GPT4: ${SERVICE_AZURE_OPENAI_PROXY_CHAT_COMPLETION_API_KEY_FOR_GPT4}
      CHAT_COMPLETION_API_VERSION_FOR_GPT4: ${SERVICE_AZURE_OPENAI_PROXY_CHAT_COMPLETION_API_VERSION_FOR_GPT4}
      # embedding
      EMBEDDING_RESOURCE: ${SERVICE_AZURE_OPENAI_PROXY_EMBEDDING_RESOURCE}
      EMBEDDING_DEPLOYMENT: ${SERVICE_AZURE_OPENAI_PROXY_EMBEDDING_DEPLOYMENT}
      EMBEDDING_API_KEY: ${SERVICE_AZURE_OPENAI_PROXY_ EMBEDDING_API_KEY}
      EMBEDDING_API_VERSION: ${SERVICE_AZURE_OPENAI_PROXY_EMBEDDING_API_VERSION}
      # image generation
      IMAGE_GENERATION_RESOURCE: ${SERVICE_AZURE_OPENAI_PROXY_IMAGE_GENERATION_RESOURCE}
      IMAGE_GENERATION_DEPLOYMENT: ${SERVICE_AZURE_OPENAI_PROXY_IMAGE_GENERATION_DEPLOYMENT}
      IMAGE_GENERATION_API_KEY: ${SERVICE_AZURE_OPENAI_PROXY_ IMAGE_GENERATION_API_KEY}
      IMAGE_GENERATION_API_VERSION: ${SERVICE_AZURE_OPENAI_PROXY_IMAGE_GENERATION_API_VERSION}
      # image edit
      IMAGE_EDIT_RESOURCE: ${SERVICE_AZURE_OPENAI_PROXY_IMAGE_EDIT_RESOURCE}
      IMAGE_EDIT_DEPLOYMENT: ${SERVICE_AZURE_OPENAI_PROXY_IMAGE_EDIT_DEPLOYMENT}
      IMAGE_EDIT_API_KEY: ${SERVICE_AZURE_OPENAI_PROXY_ IMAGE_EDIT_API_KEY}
      IMAGE_EDIT_API_VERSION: ${SERVICE_AZURE_OPENAI_PROXY_IMAGE_EDIT_API_VERSION}
      
networks:
  default:
    external: true
    name: compose-ingress
